# Generated by Django 3.2.8 on 2021-11-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
