# Generated by Django 3.2.8 on 2021-11-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_created_at_reviewrating_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
